---
- name: Download s3 file
  hosts: localhost

  tasks:
    - name: Download S3 files
      aws_s3:
        bucket: myrajinibucket
        object: employee.csv
        dest: /home/centos  Ra
        mode: get
