---
- name: Download s3 file
  hosts: appServers
  remote_user: ec2-user
  become: true

  tasks:
    - name: Download S3 files
      aws_s3:
        bucket: rajini123456
        object: /Notes
        dest: /home/ec2-user
        mode: get
