---
- name:  Execute Shell script
  hosts: appServers
  remote_user: ec2-user
  become: true
  
  tasks:
  - name: Copy the files1
    shell: touch /home/ec2-user/file123.txt
    shell: cd /home/ec2-user
    shell: echo 'sudo yum install httpd -y' > installHttpd.sh
    shell: ls -ltr
