---
- name: Download s3 file
  hosts: appServers
  remote_user: ec2-user
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3 

  tasks:
    - name: Install boto3 and botocore with pip3 module
      pip:
        name: 
        - boto3
        - botocore
        executable: pip-3.7

    - name: Download S3 files
      aws_s3:
        aws_access_key: "AKIAUVKYPQA7OYFC5V7M"
        aws_secret_key: "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"
        bucket: myrajinibucket
        object: employee.csv
        dest: /tmp
        mode: get
