---
- name: notify
  hosts: localhost
  
  tasks: 
  - name: httpd install
    yum:
      name: httpd
      state: present
    notify: installation_slack

  handlers:
  - name: installation_slack
    slack:
      #domain: apextrainingind.slack.com
      token: T02DG1XP6MN/B02CYLNFB7E/zKZvsQqsW8Ni39WEuwzWM7kv
      msg: "httpd installed"
      channel: '#apextrainingproject'
