--- 
- 
  gather_facts: false
  hosts: all
  remote_user: ec2-user
  tasks: 
    - 
      name: "Wait for SSH to come up"
      wait_for_connection: 
        delay: 5
        timeout: 90
    - 
      ec2_metadata_facts: ~
      name: "Collect instance facts"
    - 
      become: true
      name: "Install HTTPD"
      yum: 
        name: httpd
        state: present
    - 
      become: true
      name: "Start HTTPD"
      service: 
        enabled: true
        name: httpd
        state: started
    - 
      become: true
      name: "Deploy content"
      template: 
        dest: /var/www/html/index.html
        src: /home/ansible/index.html.j2
  vars_files: 
    - /home/ansible/env_vars.yml
